frontend/apps/contact/urls.py
from django.conf.urls import url

from frontend.apps.contact.api.views import ContactImportHF
from frontend.apps.contact.views import (
    ContactImportSocial, contact_list, ContactImportCS,
    ContactUploadView, ContactManagerView)


urlpatterns = [
    url(r'^/import/housefile/(?P<account_id>[^/]+)/$',
        ContactImportHF.as_view(), name='contacts_import_hf'),
    url(r'^/import/(?P<social_id>[^/]+)/$', ContactImportSocial.as_view(),
        name='contacts_import'),
    url(r'^/import/cs/(?P<source>[^/]+)/$',
        ContactImportCS.as_view(), name='contacts_import_cs'),
    url(r'^/manager/$', ContactManagerView.as_view(), name="contact_manager"),
    url(r'^/file_upload/$', ContactUploadView.as_view(),
        name="contact_file_upload"),
    url(r'^/$', contact_list, name='contact_list'),
]

frontend/apps/core/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'', include('social_django.urls', namespace='social')),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^tasks/$', views.task_info, name='task_info'),
    url(r'^task/$', views.task_status, name='task_status'),
    url(r'^terms_of_service/', views.TermsOfServiceView.as_view(),
        name='terms_of_service'),
    url(r'^getting_started/$', views.GettingStartedView.as_view(),
        name='getting_started'),
    url(r'^getting_started/(?P<forced_type>[^/]+)/$',
        views.GettingStartedView.as_view(), name='getting_started_forced'),
    url(r'^getting_started/(?P<forced_type>[^/]+)/(?P<forced_version>[^/]+)/$',
        views.GettingStartedView.as_view(), name='getting_started_forced'),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^oauth_finished/$',
        TemplateView.as_view(template_name='core/oauth_finished.html')),
    url(r'^recurly_webhook/$', views.RecurlyWebhook.as_view(), name='recurly_webhook'),
    url(r'^onboard/qualify/$',
        views.OnboardingQualifierView.as_view(), name="onboard_qualifier"),
    url(r'^onboard/refresh_token/(?P<token>[^/]+)/$',
        views.RefreshTokenView.as_view(), name="refresh_token"),
    url(r'^onboard/signup/(?P<token>[^/]+)/$',
        views.OnboardingSignupView.as_view(), name="onboard_signup"),
    url(r'^onboard/setup/(?P<account_id>[^/]+)/$',
        views.OnboardingSetupView.as_view(), name="onboard_setup")
]

frontend/apps/seat/urls.py
from django.conf.urls import url

from .views import SelectActiveSeat


urlpatterns = [
    url(r'^/select_current/$', SelectActiveSeat.as_view(),
        name="select_current_seat"),
]

frontend/urls.py
from os import environ

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from frontend.apps.authorize.views import LoginView

media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Frontend apps urls
app_urls = [
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('img/favicon.ico'),
            permanent=False),
        name="favicon"),
    url(r'^accounts', include('frontend.apps.authorize.urls')),
    url(r'^rankings/', include('frontend.apps.analysis.urls')),
    url(r'^contacts', include('frontend.apps.contact.urls')),
    url(r'^personas/', include('frontend.apps.personas.urls')),
    url(r'^campaign', include('frontend.apps.campaign.urls')),
    url(r'^events', include('frontend.apps.campaign.event_urls')),
    url(r'^contact_sets/', include('frontend.apps.contact_set.urls')),
    url(r'^seats', include('frontend.apps.seat.urls')),
    url(r'^staff_admin/', include('frontend.apps.staff_admin.urls')),
    url(r'^campaign_admin/', include('frontend.apps.campaign_admin.urls')),
    url(r'^call_time/', include('frontend.apps.call_time.urls')),
    url(r'^external_apps/', include('frontend.apps.external_app_integration.urls')),
    url(r'^', include('frontend.apps.core.urls')),
]

# API urls
# This looks complicated, but all it does is prepend '^rest/' to all the urls.
api_urls = [
    url(r'^rest/',
        include([
            # Redirects rest framework login to revup login
            url(r'^api-auth/login/', LoginView.as_view(), name='rest_api_login'),
            url(r'^api-auth/',
                include('rest_framework.urls',
                        namespace='rest_framework')),
            # URLs to the various internal APIs
            url(r'^', include("frontend.api_urls")),
        ])),
]

urlpatterns = api_urls + media + app_urls


if settings.DEBUG and not environ.get('CI'):
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

frontend/apps/analysis/models/results.py
"""Analysis result models

This module provides models for the production and storage of analysis results.
"""
import collections
import math
import time

from django.conf import settings
from django.contrib.postgres import fields
from django.core.cache import cache
from django.db import models
from django_extensions.db.models import TimeStampedModel
from jsonfield import JSONField

from frontend.libs.mixins import SimpleUnicodeMixin
from frontend.libs.utils.model_utils import (
    JSONEncoder, VirtualForeignObject, Choices)


class Analysis(TimeStampedModel, SimpleUnicodeMixin):
    """The result of an analysis for a specific user

    The results of an analysis are organized into associated Result records. An
    analysis may be organized by one or more partitions (i.e. date ranges).

    Attributes:
      user (RevUpUser): Owning user
      event (Event): Event for which this analysis was run (if any)
      account (Account): Campaign for which this analysis was run
      analysis_config (AnalysisConfig): Analysis configuration used to produce
        this analysis
      partition_set (PartitionSetConfig): Partition set configuration used to
        produce this analysis
      status (str): Status of this analysis
      timestamp (datetime): Timestamp for creation of this analysis

    """
    class STATUSES:
        running = "RUNNING"
        complete = "COMPLETE"
        error = "ERROR"
        finished = (complete, error)

    user = models.ForeignKey('authorize.RevUpUser', on_delete=models.CASCADE)
    event = models.ForeignKey('campaign.Event', on_delete=models.CASCADE, null=True,
                              related_name='+')
    account = models.ForeignKey('campaign.Account', on_delete=models.CASCADE)
    analysis_config = models.ForeignKey('analysis.AnalysisConfig', on_delete=models.CASCADE, null=True,
                                        related_name='+')
    partition_set = models.ForeignKey('analysis.PartitionSetConfig', on_delete=models.CASCADE, null=True,
                                      related_name='+')
    applied_filters = models.ManyToManyField("filtering.Filter",
                                             through="AnalysisAppliedFilter",
                                             related_name="+")
    last_completed = models.DateTimeField(
        blank=True,
        null=True,
        help_text="The last time the Analysis was completed successfully."
    )

    meta_results = JSONField(
        blank=True, default={},
        help_text="Contains the results from the meta analysis features. A "
                  "meta analysis is an analysis on the rest of the analysis")

    status = models.CharField(
        max_length=10,
        choices=(
            (STATUSES.running, STATUSES.running),
            (STATUSES.complete, STATUSES.complete),
            (STATUSES.error, STATUSES.error),
        ),
        default=STATUSES.running,
        blank=True,
    )
    task_id = models.CharField(max_length=255, null=True, blank=True)

    def is_running(self):
        return self.status == self.STATUSES.running

    def is_complete(self):
        return self.status == self.STATUSES.complete

    def get_result_count(self):
        # If this hasn't been saved, it can't have a result count
        if not self.id:
            return 0

        # Check the cache for results
        key = settings.GLOBAL_CACHE_KEYS.analysis_results_count_cache.format(
            analysis_id=self.id,
            modified=int(time.mktime(self.modified.timetuple())))
        result_count = cache.get(key, version=settings.PRODUCT_VERSION)
        if result_count:
            return result_count

        # Cache miss
        if self.is_complete() and self.results.exists():
            partition = self.partition_set.partition_configs.first()
            result_count = self.results.filter(partition=partition).count()
            cache.set(key, result_count, version=settings.PRODUCT_VERSION)
            return result_count
        else:
            return 0

    def build_partition_map(self):
        """Build a map of this analysis' partitions. These are used in views"""
        partition_set = self.partition_set
        if partition_set is None:
            # old analysis may not necessarily have partition_set populated
            partition_set = self.analysis_config.partition_set_config
        return partition_set.build_partition_map()


class AnalysisAppliedFilter(models.Model):
    class Meta:
        unique_together = ('analysis', 'filter')
    analysis = models.ForeignKey("Analysis", on_delete=models.CASCADE)
    filter = models.ForeignKey("filtering.Filter", on_delete=models.CASCADE)
    filter_configs = fields.JSONField(blank=True)


class Result(models.Model):
    """The result of an analysis for a specific target

    The results of an analysis are organized into result records. Each result
    will have a target (e.g. a person) and one or more feature results for that
    target. A result may also be associated with a partition of the analysis
    (i.e. a date range).

    Initially, only Contacts will be used as targets, until we transition to
    a more generic target Entity.

    Attributes:
      user (RevUpUser): Owning user
      contact (Contact): Contact corresponding to this result
      analysis (Analysis): Analysis for which this result was produced
      partition (PartitionConfig): Configuration for the partition this
        result is in
      features (FeatureResults): Feature results for this result
      key_signals (OrderedDict): Portions of signal data from signal sets of
        a result's features for use in result-level summaries

    """
    user = models.ForeignKey('authorize.RevUpUser', on_delete=models.CASCADE, related_name='+')
    contact = models.ForeignKey('contact.Contact', on_delete=models.CASCADE, related_name='+',
                                blank=True, null=True)
    contact_index = VirtualForeignObject(
        'filtering.ContactIndex',
        related_name='+',
        from_fields=['contact_id'],
        to_fields=['contact'],
        on_delete=models.DO_NOTHING,
        db_index=False, editable=False, blank=True, null=True)
    analysis = models.ForeignKey('Analysis', on_delete=models.CASCADE, related_name='results')
    partition = models.ForeignKey('analysis.PartitionConfig', on_delete=models.CASCADE, related_name='+',
                                  blank=True, null=True)
    key_signals = JSONField(
        # Use customized json encoder with support for ObjectIds
        dump_kwargs={'cls': JSONEncoder, 'separators': (',', ':')},
        load_kwargs={'object_pairs_hook': collections.OrderedDict})
    score = models.FloatField(default=0.0)
    giving = models.DecimalField(blank=True, decimal_places=2,
                                 max_digits=12, default=0)
    tags = fields.ArrayField(models.CharField(max_length=64),
                             default=[])

    class Meta:
        index_together = (
            ("analysis", "partition", "score"),
            ("analysis", "partition", "giving"),
        )

    def get_features(self, include_features=None, show_full_data=True,
                     demo_mode=False, limit=None, feature_flags=None):
        """Generate a list of all FeatureResults and their values."""
        feature_results = []
        has_results = set()
        for feature in self.features.select_related("feature_config__feature"):
            # If this feature is not included in the results, we skip it.
            if include_features and feature.feature_config.feature.title \
                    not in include_features:
                continue

            signal_sets = feature.formatted_data(
                show_full_data=show_full_data, demo_mode=demo_mode,
                limit=limit, analysis_config=self.analysis.analysis_config,
                feature_flags=feature_flags)

            feature_results.append((
                feature.feature_config.title,
                feature.feature_config.feature.title, signal_sets))
            has_results.add(feature.feature_config.id)

        # Add blank placeholders for any features that don't have results.
        # We don't need to do this if only certain features are requested.
        if not include_features:
            all_features = [
                (fc.title, fc.feature.title if fc.feature else None, [])
                for fc in self.analysis.analysis_config.feature_configs
                                       .select_related("feature")
                if fc.id not in has_results and not fc.hidden]
            feature_results.extend(all_features)
        return feature_results

    @classmethod
    def _log_or_zero(cls, i):
        if i <= 0:
            return 0
        else:
            return math.log(i)

    @classmethod
    def _normalize_score(cls, score, min_score, max_score):
        """Normalize the value score given a min of min_score and a max of max_score.
        """
        min_score = cls._log_or_zero(float(min_score))
        max_score = cls._log_or_zero(float(max_score))
        norm_score = cls._log_or_zero(float(score))
        try:
            norm_score = ((norm_score - min_score) /
                          float(max_score - min_score)) * 100.0
        except ZeroDivisionError:
            norm_score = score

        if norm_score < 0:
            norm_score = 0.0
        elif norm_score > 100:
            norm_score = 100.0
        score = norm_score
        return score

    @property
    def normalized_score(self):
        return self.get_normalized_score(self.analysis)

    def get_normalized_score(self, analysis):
        """Normalized score

        Normalize the score only if min and max score are found in
        meta_results. Otherwise the score is assumed to already be normalized.
        """
        score = self.score
        partition_id = str(self.partition_id)
        try:
            normalize_meta = analysis.meta_results.get(

frontend/apps/campaign_admin/models.py
from django.db import models
from django.contrib.postgres import fields

from frontend.libs.utils.model_utils import Choices


class ManagementGroup(models.Model):
    class Permissions(Choices):
        choices_map = (
            ("TR", "TRACKER", "Tracker"),
        )

    name = models.CharField(max_length=256, blank=True)
    account = models.ForeignKey("campaign.Account", on_delete=models.CASCADE)
    managers = models.ManyToManyField(
        "seat.Seat",
        blank=True,
        related_name="management_groups_manager",
        help_text="The managers of the members of this group. The permissions "
                  "field gives these users permissions over the members"
    )
    members = models.ManyToManyField(
        "seat.Seat",
        blank=True,
        related_name="management_groups_member",
        help_text="These users are managed by the managers."
    )
    permissions = fields.ArrayField(models.CharField(max_length=2,),
                                    default=[], blank=True)

    class Meta:
        unique_together = (("account", "name"),)

    def _add_seat(self, seat_attr, other_seat_attr, seat):
        """Check if the other group (e.g. members) already contains the
        given seats. If not, add them.
        """
        if getattr(self, other_seat_attr).filter(pk=seat.pk).exists():
            raise ValueError("The given seat is already in '{}'. It "
                             "cannot be in both.".format(other_seat_attr))
        else:
            getattr(self, seat_attr).add(seat)

    def add_managers(self, seat):
        self._add_seat('managers', 'members', seat)

    def add_members(self, seat):
        self._add_seat('members', 'managers', seat)

frontend/apps/core/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models


class DeleteLog(models.Model):
    request_user = models.ForeignKey("authorize.RevUpUser",
                                     on_delete=models.CASCADE, null=True,
                                     related_name="requested_deletes")
    obj_user = models.ForeignKey("authorize.RevUpUser",
                                 on_delete=models.CASCADE, null=True,
                                 related_name="+")
    account = models.ForeignKey("campaign.Account",
                                on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    data = JSONField(blank=True, default={})

    @classmethod
    def delete_contact_set(cls, contact_set, request_user=None):
        dl = DeleteLog(request_user=request_user,
                       obj_user=contact_set.user,
                       account=contact_set.account)
        dl.data = {
            "model": "ContactSet",
            "label": contact_set.title,
            "count": contact_set.count,
            "source": contact_set.Sources.translate(contact_set.source),
            "source_detail": contact_set.source_uid
        }
        dl.save()

frontend/templates/staff_admin/activate_client.html
{% extends "staff_admin/base_staff_admin.html" %}
{% load staticfiles %}
{% load revup_extras %}

{% block page_css %}
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css"/>
<link href="{% static "css/apps/contacts.css" %}" rel="stylesheet">
<link href="{% static "css/apps/create_client.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container client-content createClient">
    {% if form.non_field_errors %}
        <div class="non-field-errors">
          {% for err in form.non_field_errors %}
            <div class="alert-warning">{{ err }}</div>
          {% endfor %}
        </div>
    {% endif %}

    <div class="row row-sm-padding">
        <div class="col-md-12" style="margin-bottom:10px">
            <form id="activateClientForm" role="form" method="post">{% csrf_token %}
                <div class="col-md-8 createClientDiv">
                    <div class="panel panel-success panel-body-background">
                        <div class="panel-heading">
                            <h2 class="panel-title">Activate Client Account: </h2>
                        </div>

                        <div class="panel-body">
                            <div class="form-group">
                                {% for account in accounts %}
{#                                    <label class="control-label" for="id_activate">{{ form.activate.label }}</label>#}
                                    <input id="id_activate" name="activate" type="checkbox" value="{{ account.id }}">
                                    {{ account.organization_name }}<br>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Account Head: {{ account.account_head.first_name }} {{ account.account_head.last_name }}<br>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email: {{ account.account_head.email }}<br><br>
                                {% endfor %}
                            </div>

                            <div style="width:100%;margin-top:15px;">
                                <button class="addCampAdminBtn btn btn-primary pull-right" type="submit">Activate Selected Client(s) and Start Billing</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block page_foot_scripts %}
<script type="text/javascript" src="{% static "js/apps/event-form.js" %}"></script>
{% endblock page_foot_scripts %}

frontend/templates/staff_admin/base_staff_admin.html
{% extends "shared/sections/base_authenticated.html" %}

{% block title %}Staff Admin - RevUp{% endblock %}

{% block staff_admin %}active{% endblock %}

{% block notification %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
      <div style="margin: 5px;"
         class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}warning{% else %}success{% endif %}">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error:{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}Warning:{% endif %} {{ message }}
      </div>
    {% endfor %}
</ul>
{% endif %}
{% endblock notification %}

frontend/templates/staff_admin/home.html
{% extends "staff_admin/base_staff_admin.html" %}
{% load staticfiles %}
{% load view_router %}


{% block page_css %}
<link href="{% static "css/apps/staffAdmin.css" %}" rel="stylesheet">
{% endblock page_css %}

{% block content %}
<div class="newStaffAdminContent">
    {% if perms.authorize.can_manage_users %}
        <div class="grpBox">
            <div class="header">User Management</div>
            <div class="body">
                <div class="entry center">
                    <form action="{% url "staff_admin_create_client" %}" method="get">
                        <button class="revupBtnDefault" type="submit">Create Client</button>
                    </form>
                </div>

                <div class="entry center">
                    <form action="{% url "impersonate-search" %}" method="get">
                        <button class="revupBtnDefault" type="submit">Impersonate a User</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{#    <div class="grpBox">#}
{#        <div class="header">Analysis Tool</div>#}
{#        <div class="body">#}
{#            <div class="entry center">#}
{#                <a class="revupBtnDefault" href="{% url "staff_admin_run_analysis_for_account" %}">Run Analysis for Account</a>#}
{#            </div>#}
{##}
{#            <div class="entry center">#}
{#                <a class="revupBtnDefault" href="{% url "staff_admin_list_analysis" %}">List Analysis</a>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

    {% if perms.authorize.can_manage_database %}
        <div class="grpBox">
            <div class="header">Database</div>
            <div class="body">
                <div class=" entry center">
                    <a class="revupBtnDefault" href="{% url 'admin:index' %}" target="_blank">Django Admin</a>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.authorize.can_manage_site_modes %}
        <div class="grpBox">
            <div class="header">Site Modes</div>
            <div class="body">
                <div class="entry center">
                    <button id="btn-debug" class="revupBtnDefault" >Toggle Debug Mode</button>
                </div>
                <div class="entry center">
                    <button id="btn-demo" class="revupBtnDefault" >Toggle Demo Mode</button>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.authorize.can_manage_skinning_tools %}
        <div class="grpBox">
            <div class="header">Skinning Tool</div>
            <div class="body">
                <div class="entry center">
                    <button id="skinningBtn" class="revupBtnDefault">Skinning Popup</button>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.authorize.can_force_analysis %}
        <div class="grpBox">
            <div class="header">Force Analysis Tool</div>
            <div class="body">
                <div class="entry center">
                    <a class="revupBtnDefault" href="{% url 'network_search' %}?user_only=1">User only, Update inplace</a>
                </div>
                <div class="entry center">
                    <a class="revupBtnDefault" href="{% url 'network_search' %}?account_only=1">Account only, Update inplace</a>
                </div>
                <div class="entry center">
                    <a class="revupBtnDefault" href="{% url 'network_search' %}?user_only=1&force_new_analysis=1">User only, Force new analysis</a>
                </div>
                <div class="entry center">
                    <a class="revupBtnDefault" href="{% url 'network_search' %}?account_only=1&force_new_analysis=1">Account only, Force new analysis</a>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.authorize.can_manage_customer_success %}
        <div class="grpBox">
            <div class="header">Customer Success</div>
            <div class="body">
                <div class="entry center">
                    <form action="{% url "staff_admin_client_activation" %}" method="get">
                        <button class="revupBtnDefault" type="submit">Activate Client Account</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.authorize.can_manage_sales %}
        <div class="grpBox">
            <div class="header">Sales</div>
            <div class="body">
                <div class="entry center">
                    <form action="{% url "staff_admin_add_account_to_token" %}" method="get">
                        <button class="revupBtnDefault" type="submit">Onboard New Client</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}


</div>
{% endblock content %}

{% block extra_scripts %}
  <script type="text/javascript">
  function DisplayDebugMode() {
    var debug_state = Cookies.get("debug");
    $("#btn-debug").text(!!debug_state ? "Disable Debug Mode" : "Enable Debug Mode");
  }

  function ToggleDebugMode() {
    var debug_state = Cookies.get("debug");
    if (!!debug_state) {
      Cookies.remove("debug");
    } else {
      Cookies.set("debug", "true");
    }
    DisplayDebugMode();
  }

  $(document).ready(function () {
    DisplayDebugMode();
    $("#btn-debug").click(ToggleDebugMode);
  });
  </script>

  <script type="text/javascript">
      function DisplayDemoMode() {
        var demo_state = Cookies.get("demo");
        $("#btn-demo").text(!!demo_state ? "Disable Demo Mode" : "Enable Demo Mode");
      }

      function ToggleDemoMode() {
        var demo_state = Cookies.get("demo");
        if (!!demo_state) {
          Cookies.remove("demo");
        } else {
          Cookies.set("demo", "true");
        }
        DisplayDemoMode();
      }

      $(document).ready(function () {
        DisplayDemoMode();
        $("#btn-demo").click(ToggleDemoMode);
      });
  </script>

<script type="text/javascript" src="{% static "js/apps/skiningTool.js" %}" charset="utf-8"></script>

<script>
$('#skinningBtn').on('click', function(e) {
    var skiningTemplate = {
        // id's
        accountId:          "{{account.id}}",
        seatId:             "{{user.current_seat.id}}",
        defaultIconText:    "",

        // default image urls
        logoUrl: "{% static "img/new-revup-logo.png" %}",
        bannerUrl: "staff-skinning",

        // ajax urls
        themeLstUrl: "{% url "staff_skins_api-list" %}",
        themeSaveUrl: "{% url "staff_skins_api-detail" "themeId" %}",
        setActiveSkinUrl: "",

        // template for
        isAcademic:             true,
        isPoliticalCampaign:    true,
        isPoliticalCommittee:   true,

        // type of user
        isStaff: true,
    }
    skiningTool.load(skiningTemplate);
})
</script>
{% endblock extra_scripts %}

frontend/templates/staff_admin/list_analysis.html
{% extends "staff_admin/base_staff_admin.html" %}
{% load staticfiles %}

{% block page_css %}
<style>
table {
    width: 100%;
}
td {
    padding: 2px 10px;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
{% include 'sortable_listview/sort_links.html' %}
    <table>
        <tr>
            <th>
                id
            </th>
            <th>
                Timestamp
            </th>
            <th>
                Account
            </th>
            <th>
                Analysis Config
            </th>
        </tr>
    {% for analysis in object_list %}
        <tr>
            <td>
                <a href="{% url 'analysis_result_list' analysis.id %}">
                    {{ analysis.id }}
                </a>
            </td>
            <td>
                {{ analysis.timestamp }}
            </td>
            <td>
                {{ analysis.account }}
            </td>
            <td>
                {{ analysis.analysis_config }}
            </td>
        </tr>
    {% endfor %}
    </table>
{% include 'sortable_listview/pagination.html' %}
</div>
{% endblock content %}

frontend/templates/staff_admin/run_analysis.html
{% extends "staff_admin/base_staff_admin.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <form action="{% url 'staff_admin_run_analysis_for_account' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <input type="submit" value="Submit" />
    </form>
</div>
{% endblock content %}

{% block page_foot_scripts %}
<script type="text/javascript">
function UpdateAnalysisConfigOptions(account) {
    var account_id = $(account).val();
    var url = "{% url "analysis_configs_api-list" "_account_id_" %}".replace("_account_id_", account_id);
    if (account_id == "") {
        $("select#id_analysis_config").html($('<option>', {value: '', text: 'Select account' }));
        $("select#id_analysis_config option:first").attr('selected', 'selected');
        $("select#id_analysis_config").attr('disabled', true);
    } else {

        $.getJSON(url, function(r) {
            var options = [];

            if (r.count == 0) {
                options.push($('<option>', {value: '', text: 'No Analysis Configs' }));
            } else {
                options.push($('<option>', {value: '', text: '---------' }));

                for (var i = 0; i < r.results.length; i++) {
                    result = r.results[i];
                    options.push(
                            $('<option>', {
                                value: r.results[i].id,
                                text: r.results[i].title
                            }));
                }
            }
            $("select#id_analysis_config").html(options);
            $("select#id_analysis_config option:first").attr('selected', 'selected');
            $("select#id_analysis_config").attr('disabled', !Boolean(r.count));
        });
    }
}

$(document).ready(function () {
    UpdateAnalysisConfigOptions($("select#id_account"));
});

</script>
{% endblock page_foot_scripts %}